### ISSUE TITLE
Theme Support?

### ISSUE THREAD

**Issue by entity** [brendt/phpstorm-photon-theme#7]
Hey there,

Is it possible to be able to integrate this somehow within a theme, such as the default? I often switch between a light and dark theme, and each time I switch to default theme, I have to go in and set the colour scheme each time.

**Comment by ditshej** [comment]
I had/have the same problem. My solution was to make use of this plugin: [https://plugins.jetbrains.com/plugin/14076-auto-dark-mode](https://plugins.jetbrains.com/plugin/14076-auto-dark-mode
)
And hoping, that jetbrains will fix this somewhen in the future 😂

**Comment by entity** [comment]
> I had/have the same problem. My solution was to make use of this plugin: https://plugins.jetbrains.com/plugin/14076-auto-dark-mode
> And hoping, that jetbrains will fix this somewhen in the future 😂

Haha, oh wow. Thanks for sharing!
